os: unstable
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
artifacts:
  - path: Addon-Manager.zip
install:
  - set CI=true
  - npm install -g npm@latest
  - npm install -g electron-packager
  - npm install --production
  - set PATH=%APPDATA%\npm;%PATH%
test_script:
  - npm run package
  - 7z a Addon-Manager.zip -r dist
